name: Test output
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test_output:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Try setting output
        id: updater
        run: echo "print_value=Content is same" >> $GITHUB_OUTPUT
      - name: Print the output
        run: echo "${{ steps.updater.outputs.print_value }}"
      - name: Dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Test Git commands
        run: |
          echo "This is a test file $(date)" >> test_file.txt
          git config --local user.name  ${{ github.actor }}        
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add test_file.txt
          git commit -m "Action file test"
          git push origin ${{ github.ref_name }}
